import React, { useRef, useEffect } from 'react';
import { useLoader, useFrame } from '@react-three/fiber';
import { STLLoader } from 'three/examples/jsm/loaders/STLLoader';
import { Center, Float, Stage } from '@react-three/drei';
import * as THREE from 'three';

export function DynamicModel({ fileUrl, color = "#29b6f6" }) {
    const meshRef = useRef();

    // 1. Load the STL file generated by the backend
    const geometry = useLoader(STLLoader, fileUrl || null); // null fallback to avoid error if no url yet

    // 2. Auto-center and compute physics normals
    useEffect(() => {
        if (geometry) {
            geometry.computeVertexNormals();
            geometry.center();
        }
    }, [geometry]);

    if (!fileUrl) return null;

    return (
        <Center>
            <Float speed={2} rotationIntensity={0.5} floatIntensity={0.5}>
                <mesh ref={meshRef} geometry={geometry} castShadow receiveShadow>
                    {/* Elite PBR Material: Brushed Steel Look */}
                    <meshPhysicalMaterial
                        color={color}
                        metalness={0.9}
                        roughness={0.2}
                        clearcoat={1.0}
                        clearcoatRoughness={0.1}
                        reflectivity={1}
                        envMapIntensity={1.5}
                    />
                </mesh>
            </Float>
        </Center>
    );
}

export default DynamicModel;
